config/routes.rb
Rails.application.routes.draw do

  get 'airstrip' => 'airstrip#index'
  put 'airstrip/launch_planes'

  root 'airstrip#index'

end

app/models/airstrip.rb
class Airstrip

  def self.free?
    Plane.running.empty?
  end

  def self.busy?
    !free?
  end

  def self.start_delayed_planes
    return if Airstrip.busy?
    Plane.delayed.first.try(:start!)
  end

end

app/models/plane.rb
class Plane < ActiveRecord::Base

  has_many :plane_logs

  LAUNCHING_DURATION = 10.seconds

  include AASM

  aasm column: :state do
    state :new, initial: true
    state :delayed
    state :running
    state :flew

    after_all_transitions :log_plane_state

    event :start, before: :save_if_new, after: :perform_launching do
      transitions from: [:new, :delayed], to: :delayed, unless: :can_start?
      transitions from: [:new, :delayed], to: :running, guard: :can_start?
    end

    event :launched, after: :start_delayed_planes do
      transitions from: :running, to: :flew
    end

  end

  def can_start?
    Airstrip.free?
  end

  def log_plane_state
    plane_logs.create(state: aasm.to_state)
  end

  def perform_launching
    return false unless may_launched?
    Thread.new do
      sleep LAUNCHING_DURATION
      launched!
    end
  end

  def save_if_new
    save if new_record?
  end

  def start_delayed_planes
    Airstrip.start_delayed_planes
  end


end

app/models/plane_log.rb
class PlaneLog < ActiveRecord::Base
  belongs_to :plane
end

app/controllers/airstrip_controller.rb
class AirstripController < ApplicationController

  def index
    @last_events = 
      if params[:later_than]
        PlaneLog.order('id DESC').where('id > ?', params[:later_than])
      else
        PlaneLog.order('id DESC').limit(10)
      end
    respond_to do |format|
      format.html
      format.js { render 'events' }
    end
  end

  def launch_planes
    params[:planes_count].to_i.times.each do 
      Plane.new.start!
    end
    respond_to do |format|
      format.html { redirect_to airstrip_path }
      format.js { render nothing: true }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/airstrip_helper.rb
module AirstripHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/airstrip/_events.haml
- @last_events.each do |event|
  .event{class: event.state}
    %i
      = l event.created_at
    %strong
      = t "airstrip.plane_num", plane_id: event.plane_id
    = surround '[', ']' do
      = t "airstrip.plane_states.#{event.state}"
:coffee
  setTimeout ( ->
    $.get(url: "#{airstrip_path(later_than: @last_events.first.try(:id) || params[:later_than], format: :js)}")
    ), 3000

app/views/airstrip/index.haml
.airstrip 
  .head
    %h1.central
      = t :Airstrip
    .central
      .inline-block
        = form_tag airstrip_launch_planes_path, method: :PUT, remote: true do 
          - params[:planes_count] ||= 2
          = text_field_tag :planes_count, params[:planes_count]
          = succeed ', ' do
            %span.pluralize_me{"data-plural-one" => "#{t 'planes.without_counts', count: 1}", "data-plural-two" => "#{t 'planes.without_counts', count: 2}", "data-plural-five" => "#{t 'planes.without_counts', count: 5}"}<
              = t 'planes.without_counts', count: params[:planes_count]
          = button_tag t('plane.launch!')
  .central
    .events.inline-block
      = render 'events'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Airport</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>